# Generated by Django 4.2.3 on 2023-08-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='passworditems',
            name='other_details',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
