# Generated by Django 4.2.3 on 2023-08-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_passworditems_created_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='passworditems',
            name='space_name',
            field=models.CharField(default='Passwords', max_length=100),
        ),
    ]
