# Generated by Django 4.2.3 on 2023-08-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_passworditems_space_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passworditems',
            name='space_name',
        ),
    ]
