# Generated by Django 4.2.3 on 2023-08-11 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_passworditems_space_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='passworditems',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.space'),
        ),
    ]
