# Generated by Django 4.2.3 on 2023-08-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_passworditems_space'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PasswordItems',
            new_name='PasswordItem',
        ),
    ]
