# Generated by Django 4.2.3 on 2023-08-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_passworditems_passworditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passworditem',
            name='space',
        ),
    ]
