# Generated by Django 4.2.3 on 2023-08-13 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_passworditem_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='passworditem',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.space'),
        ),
    ]
