# Generated by Django 4.2.3 on 2023-08-15 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_passworditem_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passworditem',
            name='space',
        ),
    ]
