# Generated by Django 4.2.3 on 2023-08-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_passworditem_space'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passworditem',
            options={'ordering': ['-created_updated']},
        ),
    ]
