# Generated by Django 4.2.3 on 2024-06-04 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_passworditem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='passworditem',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
