# Generated by Django 4.2.3 on 2025-02-07 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_customuser_is_active_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='passworditem',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.space'),
        ),
    ]
